services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eng_bot_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/eng_bot_development
      TEST_DATABASE_URL: postgres://postgres:postgres@db:5432/eng_bot_test
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TG_PROXY: ${TG_PROXY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_TTS_URL: ${OPENAI_TTS_URL}
      OPENAI_TTS_MODEL: ${OPENAI_TTS_MODEL}
      OPENAI_TTS_VOICE: ${OPENAI_TTS_VOICE}
      AUDIO_OUTPUT_DIR: ${AUDIO_OUTPUT_DIR}
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
